import { Redirect } from 'expo-router';
import { useCallback, useEffect, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { ContextSwitcher } from '@/components/ContextSwitcher';
import { useAuth } from '@/features/auth/AuthProvider';
import { useWorkspace } from '@/features/workspace/WorkspaceProvider';
import { supabase } from '@/lib/supabase';
import { colors } from '@/theme/colors';

type Catalog={id:string;title:string;amount_cents:number}; type Player={id:string;name:string};
type Penalty={id:string;membership_id:string;title:string;amount_cents:number;status:string;note:string|null;assigned_at:string};
type Entry={id:string;entry_type:string;amount_cents:number;description:string;booked_at:string};
const euro=(c:number)=>new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'}).format(c/100);

export default function FundsScreen(){
 const {session}=useAuth(); const {activeWorkspace,isLoading}=useWorkspace(); const [teamId,setTeamId]=useState<string|null>(null);
 const [catalog,setCatalog]=useState<Catalog[]>([]); const [players,setPlayers]=useState<Player[]>([]); const [penalties,setPenalties]=useState<Penalty[]>([]); const [entries,setEntries]=useState<Entry[]>([]);
 const [ruleTitle,setRuleTitle]=useState(''); const [ruleAmount,setRuleAmount]=useState('5,00'); const [selectedPlayer,setSelectedPlayer]=useState<string|null>(null); const [selectedRule,setSelectedRule]=useState<string|null>(null); const [note,setNote]=useState('');
 const [entryType,setEntryType]=useState('income'); const [entryAmount,setEntryAmount]=useState(''); const [description,setDescription]=useState(''); const [error,setError]=useState<string|null>(null);
 const isAdmin=Boolean(activeWorkspace?.clubRoles.some(r=>r==='club_admin'||r==='cohort_admin')); const coachIds=activeWorkspace?.teams.filter(t=>t.roles.includes('coach')).map(t=>t.id)??[]; const canManage=Boolean(teamId&&(isAdmin||coachIds.includes(teamId)));
 useEffect(()=>{if(!teamId&&activeWorkspace?.teams[0])setTeamId(activeWorkspace.teams[0].id)},[activeWorkspace?.id]);
 const load=useCallback(async()=>{if(!supabase||!teamId)return; setError(null);
  const [c,p,e,a]=await Promise.all([supabase.from('penalty_catalog').select('id,title,amount_cents').eq('team_id',teamId).eq('active',true).order('created_at'),supabase.from('member_penalties').select('id,membership_id,title,amount_cents,status,note,assigned_at').eq('team_id',teamId).order('assigned_at',{ascending:false}),supabase.from('team_cash_entries').select('id,entry_type,amount_cents,description,booked_at').eq('team_id',teamId).order('booked_at',{ascending:false}),supabase.from('team_memberships').select('membership_id,team_membership_roles(role)').eq('team_id',teamId)]);
  const ids=(a.data??[]).filter(r=>((r.team_membership_roles??[]) as Array<{role:string}>).some(x=>x.role==='player')).map(r=>r.membership_id); const {data:ms}=ids.length?await supabase.from('memberships').select('id,profile_id').in('id',ids):{data:[]}; const profileIds=(ms??[]).map(x=>x.profile_id); const {data:ps}=profileIds.length?await supabase.from('profiles').select('id,display_name').in('id',profileIds):{data:[]};
  setCatalog((c.data??[]) as Catalog[]);setPenalties((p.data??[]) as Penalty[]);setEntries((e.data??[]) as Entry[]);setPlayers((ms??[]).map(m=>({id:m.id,name:(ps??[]).find(x=>x.id===m.profile_id)?.display_name??'Unbenannt'})));
 },[teamId]); useEffect(()=>{void load()},[load]);
 const cents=(v:string)=>Math.round(Number(v.replace(',','.'))*100);
 const createRule=async()=>{if(!supabase||!teamId)return;const {error:e}=await supabase.rpc('create_penalty_catalog_item',{target_team_id:teamId,item_title:ruleTitle,item_amount_cents:cents(ruleAmount)});if(e)setError(e.message);else{setRuleTitle('');await load()}};
 const assign=async()=>{if(!supabase||!teamId||!selectedPlayer||!selectedRule)return;const {error:e}=await supabase.rpc('assign_member_penalty',{target_team_id:teamId,target_membership_id:selectedPlayer,target_catalog_id:selectedRule,penalty_note:note});if(e)setError(e.message);else{setNote('');await load()}};
 const settle=async(id:string,status:string)=>{if(!supabase)return;const {error:e}=await supabase.rpc('settle_member_penalty',{target_penalty_id:id,new_status:status});if(e)setError(e.message);else await load()};
 const book=async()=>{if(!supabase||!teamId)return;const {error:e}=await supabase.rpc('book_team_cash_entry',{target_team_id:teamId,target_entry_type:entryType,target_amount_cents:cents(entryAmount),target_description:description});if(e)setError(e.message);else{setEntryAmount('');setDescription('');await load()}};
 if(!session)return <Redirect href="/sign-in"/>; if(!isLoading&&!activeWorkspace)return <Redirect href="/setup"/>;
 const balance=entries.reduce((s,e)=>s+e.amount_cents,0),open=penalties.filter(p=>p.status==='open').reduce((s,p)=>s+p.amount_cents,0);
 return <ScrollView contentContainerStyle={s.page}><View style={s.shell}><Text style={s.eyebrow}>MANNSCHAFTSKASSE</Text><Text style={s.title}>Kasse & Strafenkatalog</Text><Text style={s.subtitle}>Regeln, offene Strafen, Zahlungen und sonstige Buchungen nachvollziehbar je Mannschaft.</Text><ContextSwitcher/><View style={s.tabs}>{activeWorkspace?.teams.map(t=><Pressable accessibilityRole="button" key={t.id} onPress={()=>setTeamId(t.id)} style={[s.tab,teamId===t.id&&s.active]}><Text style={[s.tabText,teamId===t.id&&s.activeText]}>{t.name}</Text></Pressable>)}</View>
 <View style={s.metrics}><View style={s.metric}><Text style={s.muted}>Kassenstand</Text><Text style={s.value}>{euro(balance)}</Text></View><View style={s.metric}><Text style={s.muted}>Offene Strafen</Text><Text style={s.value}>{euro(open)}</Text></View></View>
 {canManage?<><View style={s.card}><Text style={s.cardTitle}>Strafenkatalog</Text><Text style={s.label}>Bezeichnung</Text><TextInput placeholder="Zu spät zum Training" value={ruleTitle} onChangeText={setRuleTitle} style={s.input}/><Text style={s.label}>Betrag in Euro</Text><TextInput placeholder="5,00" value={ruleAmount} onChangeText={setRuleAmount} style={s.input}/><Pressable accessibilityRole="button" disabled={ruleTitle.trim().length<2} onPress={createRule} style={s.primary}><Text style={s.primaryText}>Regel hinzufügen</Text></Pressable>{catalog.map(r=><Text key={r.id} style={s.rowText}>{r.title} · {euro(r.amount_cents)}</Text>)}</View>
 <View style={s.card}><Text style={s.cardTitle}>Strafe zuweisen</Text><Text style={s.label}>Spieler</Text><View style={s.choices}>{players.map(p=><Pressable accessibilityRole="radio" accessibilityState={{checked:selectedPlayer===p.id}} key={p.id} onPress={()=>setSelectedPlayer(p.id)} style={[s.choice,selectedPlayer===p.id&&s.active]}><Text style={[s.choiceText,selectedPlayer===p.id&&s.activeText]}>{p.name}</Text></Pressable>)}</View><Text style={s.label}>Regel</Text><View style={s.choices}>{catalog.map(r=><Pressable accessibilityRole="radio" accessibilityState={{checked:selectedRule===r.id}} key={r.id} onPress={()=>setSelectedRule(r.id)} style={[s.choice,selectedRule===r.id&&s.active]}><Text style={[s.choiceText,selectedRule===r.id&&s.activeText]}>{r.title} · {euro(r.amount_cents)}</Text></Pressable>)}</View><Text style={s.label}>Notiz</Text><TextInput placeholder="Optional" value={note} onChangeText={setNote} style={s.input}/><Pressable accessibilityRole="button" disabled={!selectedPlayer||!selectedRule} onPress={assign} style={s.primary}><Text style={s.primaryText}>Strafe eintragen</Text></Pressable></View>
 <View style={s.card}><Text style={s.cardTitle}>Ein- oder Ausgabe buchen</Text><View style={s.choices}><Pressable accessibilityRole="radio" onPress={()=>setEntryType('income')} style={[s.choice,entryType==='income'&&s.active]}><Text style={[s.choiceText,entryType==='income'&&s.activeText]}>Einnahme</Text></Pressable><Pressable accessibilityRole="radio" onPress={()=>setEntryType('expense')} style={[s.choice,entryType==='expense'&&s.active]}><Text style={[s.choiceText,entryType==='expense'&&s.activeText]}>Ausgabe</Text></Pressable></View><Text style={s.label}>Betrag</Text><TextInput placeholder="25,00" value={entryAmount} onChangeText={setEntryAmount} style={s.input}/><Text style={s.label}>Beschreibung</Text><TextInput placeholder="Getränkeverkauf" value={description} onChangeText={setDescription} style={s.input}/><Pressable accessibilityRole="button" disabled={!entryAmount||description.trim().length<2} onPress={book} style={s.primary}><Text style={s.primaryText}>Buchung speichern</Text></Pressable></View></>:null}
 <View style={s.card}><Text style={s.cardTitle}>Strafen</Text>{penalties.map(p=><View key={p.id} style={s.row}><View><Text style={s.name}>{players.find(x=>x.id===p.membership_id)?.name} · {p.title}</Text><Text style={s.muted}>{euro(p.amount_cents)} · {p.status==='open'?'Offen':p.status==='paid'?'Bezahlt':'Erlassen'}</Text></View>{canManage&&p.status==='open'?<View style={s.actions}><Pressable accessibilityRole="button" onPress={()=>settle(p.id,'paid')} style={s.pay}><Text style={s.payText}>Bezahlt</Text></Pressable><Pressable accessibilityRole="button" onPress={()=>settle(p.id,'waived')} style={s.waive}><Text>Erlassen</Text></Pressable></View>:null}</View>)}</View>
 <View style={s.card}><Text style={s.cardTitle}>Kassenbuch</Text>{entries.map(e=><View key={e.id} style={s.row}><Text style={s.name}>{e.description}</Text><Text style={[s.amount,e.amount_cents<0&&s.negative]}>{euro(e.amount_cents)}</Text></View>)}</View>{error?<Text style={s.error}>{error}</Text>:null}</View></ScrollView>;
}
const s=StyleSheet.create({page:{backgroundColor:colors.canvas,minHeight:'100%',padding:20,paddingBottom:48},shell:{alignSelf:'center',maxWidth:960,width:'100%'},eyebrow:{color:colors.blue,fontSize:11,fontWeight:'900',letterSpacing:1.4,marginTop:14},title:{color:colors.ink,fontSize:34,fontWeight:'900',marginTop:8},subtitle:{color:colors.muted,fontSize:15,marginTop:8},tabs:{flexDirection:'row',flexWrap:'wrap',gap:8,marginTop:16},tab:{borderColor:colors.border,borderRadius:10,borderWidth:1,padding:10},tabText:{color:colors.muted,fontWeight:'800'},active:{backgroundColor:colors.ink,borderColor:colors.ink},activeText:{color:colors.surface},metrics:{flexDirection:'row',gap:12,marginTop:18},metric:{backgroundColor:colors.surface,borderRadius:15,flex:1,padding:18},muted:{color:colors.muted,fontSize:12,marginTop:3},value:{color:colors.ink,fontSize:26,fontWeight:'900',marginTop:6},card:{backgroundColor:colors.surface,borderColor:colors.border,borderRadius:18,borderWidth:1,marginTop:18,padding:20},cardTitle:{color:colors.ink,fontSize:19,fontWeight:'900'},label:{color:colors.ink,fontSize:13,fontWeight:'800',marginBottom:7,marginTop:14},input:{borderColor:colors.border,borderRadius:10,borderWidth:1,padding:12},primary:{alignItems:'center',backgroundColor:colors.ink,borderRadius:11,marginTop:15,padding:13},primaryText:{color:colors.surface,fontWeight:'900'},rowText:{color:colors.muted,fontSize:13,marginTop:12},choices:{flexDirection:'row',flexWrap:'wrap',gap:8},choice:{borderColor:colors.border,borderRadius:999,borderWidth:1,paddingHorizontal:11,paddingVertical:8},choiceText:{color:colors.muted,fontSize:12,fontWeight:'800'},row:{alignItems:'center',borderTopColor:colors.border,borderTopWidth:1,flexDirection:'row',justifyContent:'space-between',paddingVertical:13},name:{color:colors.ink,fontSize:13,fontWeight:'800'},actions:{flexDirection:'row',gap:7},pay:{backgroundColor:colors.green,borderRadius:8,padding:8},payText:{color:colors.surface,fontWeight:'800'},waive:{borderColor:colors.border,borderRadius:8,borderWidth:1,padding:8},amount:{color:colors.green,fontWeight:'900'},negative:{color:'#b42318'},error:{color:'#b42318',marginTop:12}});
