import { Redirect } from 'expo-router';
import { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';

import { ContextSwitcher } from '@/components/ContextSwitcher';
import { useAuth } from '@/features/auth/AuthProvider';
import { useWorkspace } from '@/features/workspace/WorkspaceProvider';
import { supabase } from '@/lib/supabase';
import { colors } from '@/theme/colors';

const incidentLabels: Record<string,string> = { goal:'Tor', yellow_card:'Gelbe Karte', red_card:'Rote Karte', substitution:'Wechsel' };
type Plan = { id:string; team_id:string; opponent:string; event:{ title:string; starts_at:string }; match_squad_entries:Array<{membership_id:string;squad_role:string}> };
type Player = { id:string; name:string; role:string };
type Incident = { id:string;incident_type:string;minute:number;membership_id:string;related_membership_id:string|null;note:string|null };

export default function MatchReportScreen(){
 const {session}=useAuth(); const {activeWorkspace,isLoading:isWorkspaceLoading}=useWorkspace();
 const [plans,setPlans]=useState<Plan[]>([]); const [planId,setPlanId]=useState<string|null>(null); const [players,setPlayers]=useState<Player[]>([]); const [incidents,setIncidents]=useState<Incident[]>([]);
 const [goalsFor,setGoalsFor]=useState('0'); const [goalsAgainst,setGoalsAgainst]=useState('0'); const [matchMinutes,setMatchMinutes]=useState('90'); const [resultStatus,setResultStatus]=useState('completed');
 const [incidentType,setIncidentType]=useState('goal'); const [minute,setMinute]=useState('1'); const [playerId,setPlayerId]=useState<string|null>(null); const [relatedPlayerId,setRelatedPlayerId]=useState<string|null>(null); const [note,setNote]=useState('');
 const [isLoading,setIsLoading]=useState(false); const [isSubmitting,setIsSubmitting]=useState(false); const [error,setError]=useState<string|null>(null); const [success,setSuccess]=useState<string|null>(null);
 const isAdmin=Boolean(activeWorkspace?.clubRoles.some(r=>r==='club_admin'||r==='cohort_admin')); const coachIds=activeWorkspace?.teams.filter(t=>t.roles.includes('coach')).map(t=>t.id)??[];
 const selectedPlan=plans.find(p=>p.id===planId); const canManage=Boolean(selectedPlan&&(isAdmin||coachIds.includes(selectedPlan.team_id)));

 const loadPlans=useCallback(async()=>{if(!supabase||!activeWorkspace)return;setIsLoading(true);setError(null);
  const {data,error:planError}=await supabase.from('match_plans').select('id,team_id,opponent,event:events(title,starts_at,cohort_id),match_squad_entries(membership_id,squad_role)').eq('status','published').in('team_id',activeWorkspace.teams.map(t=>t.id));
  if(planError)setError(planError.message);else{const rows=(data??[]) as unknown as Plan[];setPlans(rows);if(!planId&&rows[0])setPlanId(rows[0].id)}setIsLoading(false);
 },[activeWorkspace?.id]); useEffect(()=>{void loadPlans()},[loadPlans]);

 const loadReport=useCallback(async()=>{if(!supabase||!selectedPlan)return;setIsLoading(true);setError(null);
  const ids=selectedPlan.match_squad_entries.map(e=>e.membership_id); const {data:members}=ids.length?await supabase.from('memberships').select('id,profile_id').in('id',ids):{data:[]}; const profileIds=(members??[]).map(m=>m.profile_id); const {data:profiles}=profileIds.length?await supabase.from('profiles').select('id,display_name').in('id',profileIds):{data:[]};
  setPlayers((members??[]).map(m=>({id:m.id,name:(profiles??[]).find(p=>p.id===m.profile_id)?.display_name??'Unbekannt',role:selectedPlan.match_squad_entries.find(e=>e.membership_id===m.id)?.squad_role??'bench'})));
  const [result,incidentResult]=await Promise.all([supabase.from('match_results').select('goals_for,goals_against,match_minutes,status').eq('match_plan_id',selectedPlan.id).maybeSingle(),supabase.from('match_incidents').select('id,incident_type,minute,membership_id,related_membership_id,note').eq('match_plan_id',selectedPlan.id).order('minute')]);
  if(result.data){setGoalsFor(String(result.data.goals_for));setGoalsAgainst(String(result.data.goals_against));setMatchMinutes(String(result.data.match_minutes));setResultStatus(result.data.status)}setIncidents((incidentResult.data??[]) as Incident[]);setIsLoading(false);
 },[selectedPlan?.id]); useEffect(()=>{void loadReport()},[loadReport]);

 const saveResult=async()=>{if(!supabase||!planId)return;setIsSubmitting(true);setError(null);setSuccess(null);const {error:e}=await supabase.rpc('save_match_result',{target_match_plan_id:planId,target_goals_for:Number(goalsFor),target_goals_against:Number(goalsAgainst),target_match_minutes:Number(matchMinutes),target_status:resultStatus});if(e)setError(e.message);else setSuccess('Ergebnis gespeichert');setIsSubmitting(false)};
 const addIncident=async()=>{if(!supabase||!planId||!playerId)return;setIsSubmitting(true);setError(null);setSuccess(null);const {error:e}=await supabase.rpc('add_match_incident',{target_match_plan_id:planId,target_incident_type:incidentType,target_minute:Number(minute),target_membership_id:playerId,target_related_membership_id:relatedPlayerId,incident_note:note});if(e)setError(e.message);else{setNote('');setRelatedPlayerId(null);await loadReport()}setIsSubmitting(false)};
 const removeIncident=async(id:string)=>{if(!supabase)return;const {error:e}=await supabase.rpc('delete_match_incident',{target_incident_id:id});if(e)setError(e.message);else await loadReport()};
 const name=(id:string)=>players.find(p=>p.id===id)?.name??'Unbekannt';
 if(!session)return <Redirect href="/sign-in"/>;if(!isWorkspaceLoading&&!activeWorkspace)return <Redirect href="/setup"/>;
 return <ScrollView contentContainerStyle={s.page}><View style={s.shell}><Text style={s.eyebrow}>SPIELBERICHT</Text><Text style={s.title}>Ergebnis & Ereignisse</Text><Text style={s.subtitle}>Endstand, Torschützen, Vorlagen, Karten und Wechsel bilden die Grundlage für die Saisonstatistik.</Text><ContextSwitcher/>
 {isLoading?<ActivityIndicator color={colors.blue} style={s.loader}/>:null}{plans.length===0&&!isLoading?<View style={s.card}><Text style={s.cardTitle}>Keine veröffentlichte Aufstellung</Text></View>:null}
 <View style={s.choices}>{plans.map(p=><Pressable accessibilityRole="button" key={p.id} onPress={()=>setPlanId(p.id)} style={[s.choice,planId===p.id&&s.active]}><Text style={[s.choiceText,planId===p.id&&s.activeText]}>{p.event.title} · {p.opponent}</Text></Pressable>)}</View>
 {selectedPlan?<><View style={s.card}><Text style={s.cardTitle}>{selectedPlan.event.title} gegen {selectedPlan.opponent}</Text><View style={s.score}><TextInput accessibilityLabel="Eigene Tore" value={goalsFor} onChangeText={setGoalsFor} style={s.scoreInput}/><Text style={s.colon}>:</Text><TextInput accessibilityLabel="Gegnerische Tore" value={goalsAgainst} onChangeText={setGoalsAgainst} style={s.scoreInput}/></View><Text style={s.label}>Spieldauer in Minuten</Text><TextInput placeholder="90" value={matchMinutes} onChangeText={setMatchMinutes} style={s.input}/><Text style={s.label}>Status</Text><View style={s.choices}>{[{value:'completed',label:'Beendet'},{value:'abandoned',label:'Abgebrochen'}].map(option=><Pressable accessibilityRole="radio" key={option.value} onPress={()=>setResultStatus(option.value)} style={[s.choice,resultStatus===option.value&&s.active]}><Text style={[s.choiceText,resultStatus===option.value&&s.activeText]}>{option.label}</Text></Pressable>)}</View>{canManage?<Pressable accessibilityRole="button" disabled={isSubmitting} onPress={saveResult} style={s.primary}><Text style={s.primaryText}>Ergebnis speichern</Text></Pressable>:null}</View>
 {canManage?<View style={s.card}><Text style={s.cardTitle}>Ereignis hinzufügen</Text><Text style={s.label}>Art</Text><View style={s.choices}>{Object.entries(incidentLabels).map(([value,label])=><Pressable accessibilityRole="radio" key={value} onPress={()=>{setIncidentType(value);setRelatedPlayerId(null)}} style={[s.choice,incidentType===value&&s.active]}><Text style={[s.choiceText,incidentType===value&&s.activeText]}>{label}</Text></Pressable>)}</View><Text style={s.label}>Minute</Text><TextInput placeholder="1" value={minute} onChangeText={setMinute} style={s.input}/><Text style={s.label}>{incidentType==='substitution'?'Ausgewechselt':'Spieler'}</Text><View style={s.choices}>{players.map(p=><Pressable accessibilityRole="radio" key={p.id} onPress={()=>setPlayerId(p.id)} style={[s.choice,playerId===p.id&&s.active]}><Text style={[s.choiceText,playerId===p.id&&s.activeText]}>{p.name} · {p.role==='starting'?'Startelf':'Bank'}</Text></Pressable>)}</View>{incidentType==='goal'||incidentType==='substitution'?<><Text style={s.label}>{incidentType==='goal'?'Vorlage (optional)':'Eingewechselt'}</Text><View style={s.choices}>{incidentType==='goal'?<Pressable accessibilityRole="radio" onPress={()=>setRelatedPlayerId(null)} style={[s.choice,relatedPlayerId===null&&s.active]}><Text style={[s.choiceText,relatedPlayerId===null&&s.activeText]}>Keine Vorlage</Text></Pressable>:null}{players.filter(p=>p.id!==playerId).map(p=><Pressable accessibilityRole="radio" key={p.id} onPress={()=>setRelatedPlayerId(p.id)} style={[s.choice,relatedPlayerId===p.id&&s.active]}><Text style={[s.choiceText,relatedPlayerId===p.id&&s.activeText]}>{p.name}</Text></Pressable>)}</View></>:null}<Text style={s.label}>Notiz</Text><TextInput placeholder="Optional" value={note} onChangeText={setNote} style={s.input}/><Pressable accessibilityRole="button" disabled={!playerId||(incidentType==='substitution'&&!relatedPlayerId)||isSubmitting} onPress={addIncident} style={s.primary}><Text style={s.primaryText}>Ereignis speichern</Text></Pressable></View>:null}
 <View style={s.card}><Text style={s.cardTitle}>Spielverlauf</Text>{incidents.length===0?<Text style={s.empty}>Noch keine Ereignisse erfasst.</Text>:incidents.map(i=><View key={i.id} style={s.row}><View><Text style={s.rowTitle}>{i.minute}. · {incidentLabels[i.incident_type]} · {name(i.membership_id)}</Text><Text style={s.meta}>{i.incident_type==='goal'&&i.related_membership_id?`Vorlage: ${name(i.related_membership_id)}`:i.incident_type==='substitution'&&i.related_membership_id?`Eingewechselt: ${name(i.related_membership_id)}`:i.note??''}</Text></View>{canManage?<Pressable accessibilityRole="button" onPress={()=>removeIncident(i.id)} style={s.delete}><Text style={s.deleteText}>Löschen</Text></Pressable>:null}</View>)}</View></>:null}{success?<Text style={s.success}>{success}</Text>:null}{error?<Text style={s.error}>{error}</Text>:null}</View></ScrollView>;
}
const s=StyleSheet.create({page:{backgroundColor:colors.canvas,minHeight:'100%',padding:20,paddingBottom:48},shell:{alignSelf:'center',maxWidth:960,width:'100%'},eyebrow:{color:colors.blue,fontSize:11,fontWeight:'900',letterSpacing:1.4,marginTop:14},title:{color:colors.ink,fontSize:34,fontWeight:'900',marginTop:8},subtitle:{color:colors.muted,fontSize:15,lineHeight:22,marginTop:8},loader:{marginTop:20},card:{backgroundColor:colors.surface,borderColor:colors.border,borderRadius:18,borderWidth:1,marginTop:18,padding:20},cardTitle:{color:colors.ink,fontSize:19,fontWeight:'900'},choices:{flexDirection:'row',flexWrap:'wrap',gap:8,marginTop:12},choice:{borderColor:colors.border,borderRadius:999,borderWidth:1,paddingHorizontal:11,paddingVertical:8},choiceText:{color:colors.muted,fontSize:12,fontWeight:'800'},active:{backgroundColor:colors.blue,borderColor:colors.blue},activeText:{color:colors.surface},score:{alignItems:'center',flexDirection:'row',gap:12,justifyContent:'center',marginTop:18},scoreInput:{borderColor:colors.border,borderRadius:12,borderWidth:1,color:colors.ink,fontSize:30,fontWeight:'900',padding:12,textAlign:'center',width:82},colon:{color:colors.ink,fontSize:30,fontWeight:'900'},label:{color:colors.ink,fontSize:13,fontWeight:'800',marginBottom:7,marginTop:15},input:{borderColor:colors.border,borderRadius:10,borderWidth:1,color:colors.ink,padding:12},primary:{alignItems:'center',backgroundColor:colors.ink,borderRadius:11,marginTop:16,padding:13},primaryText:{color:colors.surface,fontWeight:'900'},row:{alignItems:'center',borderTopColor:colors.border,borderTopWidth:1,flexDirection:'row',justifyContent:'space-between',paddingVertical:13},rowTitle:{color:colors.ink,fontSize:13,fontWeight:'900'},meta:{color:colors.muted,fontSize:11,marginTop:3},delete:{borderColor:colors.border,borderRadius:8,borderWidth:1,padding:7},deleteText:{color:'#b42318',fontSize:11,fontWeight:'800'},empty:{color:colors.faint,marginTop:15},success:{color:colors.green,fontWeight:'900',marginTop:14},error:{color:'#b42318',marginTop:14}});
