import { Redirect, useRouter } from 'expo-router';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';

import { ContextSwitcher } from '@/components/ContextSwitcher';
import { useAuth } from '@/features/auth/AuthProvider';
import { useWorkspace } from '@/features/workspace/WorkspaceProvider';
import { supabase } from '@/lib/supabase';
import { colors } from '@/theme/colors';

const categoryLabels:Record<string,string>={event:'Termin',lineup:'Aufstellung',training:'Training',penalty:'Kasse'};
type Notification={id:string;category:string;title:string;body:string;href:string;read_at:string|null;created_at:string};
const formatDate=(value:string)=>new Intl.DateTimeFormat('de-DE',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value));

export default function NotificationsScreen(){
 const router=useRouter();const {session}=useAuth();const {activeWorkspace,isLoading:isWorkspaceLoading}=useWorkspace();const [items,setItems]=useState<Notification[]>([]);const [filter,setFilter]=useState('all');const [isLoading,setIsLoading]=useState(false);const [error,setError]=useState<string|null>(null);
 const load=useCallback(async()=>{if(!supabase||!activeWorkspace||!session)return;setIsLoading(true);setError(null);const {data:membership,error:membershipError}=await supabase.from('memberships').select('id').eq('club_id',activeWorkspace.clubId).eq('profile_id',session.user.id).maybeSingle();if(membershipError||!membership){setError(membershipError?.message??'Mitgliedschaft nicht gefunden.');setIsLoading(false);return}const {data,error:notificationError}=await supabase.from('notifications').select('id,category,title,body,href,read_at,created_at').eq('membership_id',membership.id).order('created_at',{ascending:false});if(notificationError)setError(notificationError.message);else setItems((data??[]) as Notification[]);setIsLoading(false)},[activeWorkspace?.id,session?.user.id]);useEffect(()=>{void load()},[load]);
 const unread=items.filter(item=>!item.read_at).length;const visible=useMemo(()=>filter==='all'?items:filter==='unread'?items.filter(item=>!item.read_at):items.filter(item=>item.category===filter),[filter,items]);
 const open=async(item:Notification)=>{if(!supabase)return;if(!item.read_at)await supabase.rpc('mark_notification_read',{target_notification_id:item.id});router.push(item.href as never)};
 const markAll=async()=>{if(!supabase||!activeWorkspace)return;const {error:markError}=await supabase.rpc('mark_all_notifications_read',{target_club_id:activeWorkspace.clubId});if(markError)setError(markError.message);else await load()};
 if(!session)return <Redirect href="/sign-in"/>;if(!isWorkspaceLoading&&!activeWorkspace)return <Redirect href="/setup"/>;
 return <ScrollView contentContainerStyle={s.page}><View style={s.shell}><Text style={s.eyebrow}>BENACHRICHTIGUNGEN</Text><Text style={s.title}>Deine Zentrale</Text><Text style={s.subtitle}>Termine, Nominierungen, Vorgaben und Strafen an einem Ort – mit direktem Sprung in den passenden Bereich.</Text><ContextSwitcher/><View style={s.summary}><View><Text style={s.summaryValue}>{unread}</Text><Text style={s.summaryLabel}>ungelesen</Text></View>{unread>0?<Pressable accessibilityRole="button" onPress={markAll} style={s.markAll}><Text style={s.markAllText}>Alle als gelesen markieren</Text></Pressable>:null}</View><View style={s.filters}>{[['all','Alle'],['unread','Ungelesen'],['event','Termine'],['lineup','Aufstellungen'],['training','Training'],['penalty','Kasse']].map(([value,label])=><Pressable accessibilityRole="button" key={value} onPress={()=>setFilter(value!)} style={[s.filter,filter===value&&s.active]}><Text style={[s.filterText,filter===value&&s.activeText]}>{label}</Text></Pressable>)}</View>{isLoading?<ActivityIndicator color={colors.blue} style={s.loader}/>:null}{!isLoading&&visible.length===0?<View style={s.card}><Text style={s.empty}>Keine Benachrichtigungen in diesem Filter.</Text></View>:null}{visible.map(item=><Pressable accessibilityRole="button" key={item.id} onPress={()=>open(item)} style={[s.card,!item.read_at&&s.unreadCard]}><View style={s.cardTop}><Text style={s.category}>{categoryLabels[item.category]}</Text>{!item.read_at?<Text style={s.dot}>NEU</Text>:null}</View><Text style={s.itemTitle}>{item.title}</Text><Text style={s.body}>{item.body}</Text><Text style={s.date}>{formatDate(item.created_at)}</Text></Pressable>)}{error?<Text style={s.error}>{error}</Text>:null}</View></ScrollView>;
}
const s=StyleSheet.create({page:{backgroundColor:colors.canvas,minHeight:'100%',padding:20,paddingBottom:48},shell:{alignSelf:'center',maxWidth:820,width:'100%'},eyebrow:{color:colors.blue,fontSize:11,fontWeight:'900',letterSpacing:1.4,marginTop:14},title:{color:colors.ink,fontSize:34,fontWeight:'900',marginTop:8},subtitle:{color:colors.muted,fontSize:15,lineHeight:22,marginTop:8},summary:{alignItems:'center',backgroundColor:colors.ink,borderRadius:18,flexDirection:'row',justifyContent:'space-between',marginTop:18,padding:20},summaryValue:{color:colors.surface,fontSize:30,fontWeight:'900'},summaryLabel:{color:colors.surface,fontSize:12,marginTop:3},markAll:{backgroundColor:colors.surface,borderRadius:10,padding:10},markAllText:{color:colors.ink,fontSize:12,fontWeight:'900'},filters:{flexDirection:'row',flexWrap:'wrap',gap:8,marginTop:16},filter:{borderColor:colors.border,borderRadius:999,borderWidth:1,paddingHorizontal:11,paddingVertical:8},filterText:{color:colors.muted,fontSize:12,fontWeight:'800'},active:{backgroundColor:colors.blue,borderColor:colors.blue},activeText:{color:colors.surface},loader:{marginTop:22},card:{backgroundColor:colors.surface,borderColor:colors.border,borderRadius:16,borderWidth:1,marginTop:12,padding:17},unreadCard:{borderColor:colors.blue,borderLeftWidth:5},cardTop:{alignItems:'center',flexDirection:'row',justifyContent:'space-between'},category:{color:colors.blue,fontSize:10,fontWeight:'900',letterSpacing:1},dot:{backgroundColor:colors.blueSoft,borderRadius:999,color:colors.blue,fontSize:9,fontWeight:'900',paddingHorizontal:8,paddingVertical:4},itemTitle:{color:colors.ink,fontSize:16,fontWeight:'900',marginTop:8},body:{color:colors.muted,fontSize:13,marginTop:4},date:{color:colors.faint,fontSize:10,marginTop:9},empty:{color:colors.faint},error:{color:'#b42318',marginTop:14}});
